/**
 * 전체 에러 코드 레지스트리
 * 모든 서비스(Flutter, Admin, AI)가 참조하는 Single Source of Truth
 */
export const ErrorCodes = {
    // Auth
    INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
    EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",
    ACCOUNT_SUSPENDED: "ACCOUNT_SUSPENDED",
    ACCOUNT_LOCKED: "ACCOUNT_LOCKED",
    DEVICE_ALREADY_UPGRADED: "DEVICE_ALREADY_UPGRADED",
    CANNOT_LOGIN: "CANNOT_LOGIN",
    INVALID_REFRESH_TOKEN: "INVALID_REFRESH_TOKEN",
    TOKEN_REVOKED: "TOKEN_REVOKED",
    EMAIL_ALREADY_VERIFIED: "EMAIL_ALREADY_VERIFIED",

    // User
    INVALID_WEEKLY_GOAL: "INVALID_WEEKLY_GOAL",
    USER_ALREADY_ACTIVE: "USER_ALREADY_ACTIVE",
    USER_ALREADY_INACTIVE: "USER_ALREADY_INACTIVE",

    // Assessment
    INVALID_ASSESSMENT_STATUS: "INVALID_ASSESSMENT_STATUS",

    // General
    INTERNAL_ERROR: "INTERNAL_ERROR",
    SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
    VALIDATION_ERROR: "VALIDATION_ERROR",

    // AI Analysis
    ANALYSIS_ERROR: "ANALYSIS_ERROR",
} as const

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes]
